/* auto-generated by NAPI-RS */
/* eslint-disable */

/** An act: its name, which a control takes, and what it comes to, which JavaScript awaits. */
export declare class Act {
  get id(): string
  toString(): string
  toJSON(): string
  then<R = unknown, E = never>(onfulfilled?: ((value: unknown) => R | PromiseLike<R>) | null, onrejected?: ((reason: unknown) => E | PromiseLike<E>) | null): Promise<R | E>
}
export type JsAct = Act

/** One engine, held on the thread of JavaScript. */
export declare class Engine {
  /**
   * An engine, opened from the record, on these ears, each a generator of JavaScript or an ear of the crate under
   * the name the engine hears it by, in the order the engine offers them a question.
   */
  static boot(record: unknown[], ears: Array<[string, Generator<unknown, unknown, unknown> | NativeEar]>): Engine
  /**
   * A life opened as every host of the crate opens one: on its record, on these ears of the host, each a generator
   * of JavaScript or an ear of the crate, and then on the ears of the crate and of the extensions. A life whose
   * record drifted is refused.
   */
  static open(ears: Array<[string, Generator<unknown, unknown, unknown> | NativeEar]>, opening: Opening): Engine
  /** The record the life opened on, which the journal said again whole before boot returned. */
  get record(): unknown[]
  get root(): string
  /** What boot raised, and nothing when it raised nothing. After a drift the life goes on, with nothing kept. */
  get raised(): { is: string; args: unknown[] } | null
  get disposed(): boolean
  /**
   * Who speaks in the life, and who speaks from now on when a name is given: the site of the contract, which the work
   * an ear began sets to the name of that ear before it speaks.
   */
  site(value?: string | undefined | null): string
  /** One name of the engine, said by its name with these words, and what it gave. */
  verb(name: string, args?: unknown[], kwargs?: Record<string, unknown>): unknown
  /** One callable the engine made, called back by the number it went out under, with these words. */
  made(n: number, args?: unknown[], kwargs?: Record<string, unknown>): unknown
  /** A callable the engine made, forgotten: the host holds its number no more. */
  forget(n: number): void
  /** What an act comes to, which JavaScript awaits. */
  result<T = unknown>(act: string): Promise<T>
  /** What an act came to, and whether it is done. */
  outcome(act: string): Outcome
  /**
   * The work that an earlier life left, which waits for a wake that this life says, each act by its name and its
   * kind, as the engine of the crate finds it.
   */
  pending(): Array<[string, string]>
  /** One name of a chain, the root when none is given, read without calling it. */
  inspect(name: string, chain?: string | undefined | null): Inspection
  /** Every name the module of a chain binds, the root when none is given, in the order it bound them. */
  names(chain?: string | undefined | null): Array<string>
  /**
   * The engine is gone, and every result JavaScript awaits of it is refused. Its ears go with it: a command of the
   * crate ends, a wait ends, and the store lets its record go.
   */
  dispose(): void
  /** The way to say a fact from what is no ear: a word through its verbs, the operator, and the work an ear began, which speaks from its own loop; the fact is said to the living, whole as the bus made it, and given back. */
  say(kind: string, about: string, words?: unknown[]): [string, string, string, ...unknown[]]
  /** The way to make a question: it takes a name when it is made, it is put to the ears, its ear, when it has one, is brought to life under that name and given the name, and the name is given back, which is the act to whoever holds it. */
  act(kind: string, on: string, ear: unknown, words?: unknown[]): Act & PromiseLike<unknown>
  /** The other way to speak: a generator is brought to life under a name, and from then it hears every fact that is said and says its own. */
  drive(g: Generator<unknown, unknown, unknown> | NativeEar, name: string): void
  /** transcript gives the facts on a chain, each of which the life adds when it is said, so a chain reads at once what it said itself. */
  transcript(options?: { on?: string } | null): Array<[string, string, string, ...unknown[]]>
  /** The way to put a question that is answered now: it makes the act, and gives back what the act came to. */
  ask(kind: string, on: string, words?: unknown[]): unknown
  /** span(lo, hi) is the show of the lines lo through hi, where a line under one is counted back from the end, so that span(1, 20) is the first twenty lines and span(-20, -1) is the last twenty. */
  span(lo: number, hi: number): unknown
  /** grep(pattern) is the show of the lines that the pattern matches. */
  grep(pattern: string): unknown
  /** differs(lines) is the show of the lines that differ from the lines it holds, which is what a write shows of what came back. */
  differs(old: string[]): unknown
  /** take keeps the acts it names and everything they made. */
  take(ids?: string[], options?: { inside?: boolean } | null): unknown
  /** A read: whoever serves the path answers it with the text of it, which the read tells by the lines its show picks. */
  read(path: string, options?: { show?: unknown; on?: string } | null): TextValue
  /** A write: whoever serves the path of the text takes its content. */
  write(text: TextValue, options?: { on?: string } | null): TextValue
  /** What the act it is at came to, as the record stands where the call is made, which it gives and never raises. */
  peek(at: string, options?: { waiting?: unknown } | null): unknown
  /** The turns of a chain, folded from what it has heard. */
  turns(options?: { on?: string } | null): Array<['user' | 'assistant', string, [number, number, number, number, number] | null, unknown]>
  /** module gives the globals of a chain: the dict that the last module of its transcript carries, in which every rung of the chain runs. */
  module(options?: { on?: string } | null): unknown
  /** program gives the program of a chain: the word of every rung that runs on it since its last module, as python, each under the name of the rung that the word first ran in, which is the rung itself, the rung that a rung which retells retells, or a told rung, in order, as the runs of its transcript say. */
  program(options?: { on?: string } | null): unknown
  /** standing gives what the chains stand on: the answer of the last stand that the transcript of the root holds, and an empty standing before the first. */
  standing(): unknown
  /** stand asks the World what the chains stand on and gives the answer, which boot does on the root at the tip of every life. */
  stand(options?: { on?: string } | null): unknown
  /** clock gives one reading of the wall clock of the World. */
  clock(options?: { on?: string } | null): number
  /** chance gives a number that is at least zero and under one. */
  chance(options?: { on?: string } | null): number
  /** Whether the word of a rung may run: the gate reads it after the program of its chain, and it finds nothing when the word may run. */
  gate(word: string, options?: { on?: string } | null): string[]
  /** A cd: the paths of its chain resolve against the directory it came to from then on, and it does nothing else. */
  cd(path: string, options?: { on?: string } | null): string
  /** The working directory of a chain is the directory that the closest cd back in its transcript came to. */
  cwd(options?: { on?: string } | null): string
  /** The act again, from its name: whoever holds the name of an act is given the act the life holds under it, whole as it stands. */
  get(about: string): [string, string, string, ...unknown[]] | null
  /** A pause: while it stands, nothing it is over hears, and what is said meanwhile waits for the wake. */
  pause(id: string): void
  /** A wake: it ends the pause over the same act, and what waited is heard. */
  wake(id: string): void
  /** A cancel of that prompt reaches the acts that its rungs made on the chain with a source. */
  cancel(id: string): void
  /** An act ended from outside, by its name, with a value: it is done with it, and it ends what it made, since a close is a cancel that carries what the act it names is done with. */
  close(value: unknown, options?: { id?: string } | null): void
  /** What a word tells of itself as it runs: each interpolation of a template, with its expression and its value. */
  debug(template: Array<[string, unknown]>): void
  /** A wait: the World takes it and says it is done when its seconds have passed, and it is over then. */
  wait(options?: { seconds?: number; on?: string } | null): Act & PromiseLike<null>
  /** The run of a word on a chain: a word its caller wrote, which it tells, since nothing else did; or, with no word, a turn of a model, which its chain asks for at the turn it gives it and which the World answers, of which it tells nothing, since that turn stands as the turn it is. */
  rung(options?: { word?: string; retells?: string; actor?: string; on?: string } | null): Act & PromiseLike<unknown>
  /** A prompt: it makes the rung of one turn of its model, makes another while the rung it made gives no value, and is done with the value, so a rung whose word is refused and a rung whose word raises are asked again alike. */
  prompt(shape: unknown, options?: { message?: string; to?: string; on?: string } | null): Act & PromiseLike<unknown>
  /** chain says what a chain does: how it is opened, what it tells, and what it answers for. */
  chain(options?: { label?: string; source?: string; filter?: unknown; on?: string } | null): Act & PromiseLike<unknown>
  /** A ceiling on a chain, in dollars, in the share of the window that one answer fills, or both: it holds the ledger of the chain from the moment it is made, the dollars of the answers since then and the share of the window the last one filled, and it tells that ledger at each answer of a model, so no turn a reply has sent grows a line after it. */
  grant(options?: { usd?: number; share?: number; on?: string } | null): Act & PromiseLike<null>
  /** A command: its streams as they come, its exit, the door of its streams and of its stdin, and what it came to. */
  bash(command: string, options?: { fed?: boolean; timeout?: number; show?: unknown; show_err?: unknown; on?: string } | null): Act & PromiseLike<ExitValue>
}
export type JsEngine = Engine

/**
 * An ear that the crate writes: given once, to the boot of an engine or to a verb that takes an ear. It is let go
 * when it is disposed, so what it holds goes: a command ends, a wait ends, and a store lets its record go. The
 * engine of python steps it as a generator of its own too.
 *
 * It stays on the thread that made it: python refuses a reach of it from another thread, and a drop of it on
 * another thread frees nothing, which leaves memory alone once the ear is disposed.
 */
export declare class NativeEar {
  /**
   * The ear is let go before any engine hears it, or after the life it heard in, so what it holds goes: a command
   * ends, a wait ends, and a store lets its record go.
   */
  dispose(): void
}

/**
 * A line of the operator as a value of the shape a prompt wants, by the rules every console of the crate reads a
 * line by, as the record keeps it; or the refusal of a line that is no value of the shape, and of a shape the
 * operator answers not.
 */
export declare function answered(shape: string, line: string): unknown

/** An image copied into a directory of images under the digest of its bytes, as a message attaches it. */
export declare function attachImage(directory: string, path: string): ImageAttachment

/** The ear of commands, which runs each in a shell of this machine. */
export declare function bash(): NativeEar

/**
 * One verb of the engine, called by its name with its words by the ear or the function of the host that a life
 * hears now, and what it gave. Who speaks is the verb `spoken`, and a callable the engine made is the verb `made`,
 * with its number and its words.
 */
export declare function call(verb: string, args?: unknown[], kwargs?: Record<string, unknown>): unknown

/**
 * The config directory of the user for this process, where the configs, the extensions of the user and the
 * preferences of the TUI stand.
 */
export declare function configDirectory(): string

/** One line of a record, read with every number exact, as the record keeps it. */
export declare function decodeRecord(line: string): unknown

/** The extensions that a life runs, in the order it enabled them, as the facts of its root say them. */
export declare function enabled(root: unknown[][]): Array<Extension>

/**
 * The engine: the one file the sandbox runs, and the whole system prompt of a model.
 *
 * The crate carries the same file the python package ships, so the engine a host runs and the engine a model
 * reads are one thing.
 */
export declare const ENGINE: string

/** An extension: its name, its word, and its life word, which is empty when it has none. */
export interface Extension {
  name: string
  word: string
  life: string
}

/**
 * The ear of the extensions, given each extension that the life runs: it enables each at the tip of the life,
 * unless the record enables it, and plays each as a rung on each chain.
 */
export declare function extensions(given: Array<Extension>): NativeEar

/** The ear of the files, which reads and writes a path. */
export declare function files(): NativeEar

/**
 * The gate of the crate: what the type checker of monty found on a sheet, each error by its line, and no warning.
 * The checker is the one every engine of this thread gates with, so a word is judged once and the same.
 */
export declare function gate(sheet: string): Array<[number, string]>

/**
 * Whether a life of this thread hears an ear or a function of the host now, so that a verb said now is said by
 * what it hears.
 */
export declare function hearing(): boolean

/**
 * An image a host attached: the name of its file, the uri a message names it by, its media type, and its size in
 * bytes.
 */
export interface ImageAttachment {
  name: string
  uri: string
  mimeType: string
  size: number
}

/** The bytes of the image of a uri, as base64, and its media type, once the bytes have the digest the uri names. */
export declare function imageContent(directory: string, uri: string): ImageContent

/** The bytes of an image as base64, and its media type. */
export interface ImageContent {
  data: string
  mimeType: string
}

/** The file that holds the image of a uri, and the digest its bytes have. */
export declare function imagePath(directory: string, uri: string): ImagePath

/** The file that holds an image, and the digest its bytes have. */
export interface ImagePath {
  path: string
  digest: string
}

/** How a message names an image: `![name](uri)`. */
export declare function imageReference(name: string, uri: string): string

/** Each image a message names, as its text in the message, its name, and its uri. */
export declare function imageReferences(message: string): Array<Named>

/** The type of an image by its first bytes: its media type and its extension, for a PNG, a JPEG, a GIF or a WebP. */
export declare function imageType(data: Uint8Array): ImageType

/** The type of an image: its media type and its extension. */
export interface ImageType {
  mimeType: string
  extension: string
}

/**
 * One name of a chain, read without calling it: the name, the name of its type, its representation in the sandbox,
 * and its value, which crosses as every value does.
 */
export interface Inspection {
  name: string
  kind: string
  representation: string
  value: unknown
}

/** What the store kept at a path, read with no lease and changed in nothing. */
export declare function kept(path: string): unknown[]

/** The levels of effort, from least to most, which an actor names after its model. */
export declare function levels(): Array<string>

/** The ear of the memory extension, which finds the memory of a path in its folders and in the config directory. */
export declare function memory(config: string): NativeEar

/**
 * The model the catalog knows by a name, as `provider:id` or as an id that one model alone holds, whether it offers
 * that model or not; nothing when it knows none.
 */
export declare function model(name: string): ModelInfo | null

/**
 * A model of the catalog, as a host reads it: its name, its efforts, its window in tokens, whether it takes an
 * image, and its price in dollars for a million tokens read, written, read from the cache and written to it.
 */
export interface ModelInfo {
  name: string
  efforts: Array<string>
  window: number
  images: boolean
  price?: Array<number>
}

/**
 * The models the catalog of this machine offers, with the claude command line at a path when it is given, each
 * named as the catalog names it.
 */
export declare function models(claude?: string | undefined | null): Array<ModelInfo>

/** An image a message names: its text in the message, its name, and its uri. */
export interface Named {
  text: string
  name: string
  uri: string
}

/** The official extensions, in the order a life runs them. */
export declare function official(): Array<Extension>

/**
 * Call back when the console of Windows ends this process: at Ctrl+Break, at the close of the console, at a logoff
 * and at a shutdown, with the name of the event: `break`, `close`, `logoff` or `shutdown`. The system holds the
 * process until the callback ends it, or, at a close, a logoff or a shutdown, until the system's own limit. A later
 * callback replaces an earlier one. Ctrl+C stays SIGINT, which the host hears as a signal. A system that is not
 * Windows has no such console, and gives this callback no event.
 */
export declare function onConsoleEnd(callback: (event: "break" | "close" | "logoff" | "shutdown") => void): void

/**
 * The record a life opens on, and the ears of the crate that it hears after the ears of the host, as every host
 * of the crate opens a life: the provider, the extensions, each official extension, the files, the commands, time,
 * and the store of the record when the life keeps.
 */
export declare function opened(opening?: Opening | undefined | null): [unknown[], Array<[string, NativeEar]>]

/**
 * What a life is opened on, which every host gives the same: the directory it stands on, the record it opens on and
 * whether it keeps what it says there, whether it does work or only inspects its record, whether it enables the
 * extensions that the configs turn on, the config directory of the user, and what its provider offers. Each part
 * that is unsaid takes the default it names.
 */
export interface Opening {
  /**
   * The directory the life stands on, which each chain stands in until it goes elsewhere, and whose config turns
   * extensions on.
   */
  directory: string
  /** The record the life opens on; none when unsaid. */
  record?: string
  /**
   * Whether the life keeps what it says to its record, under the lease of the store; true when unsaid. A life that
   * keeps nothing reads its record with no lease.
   */
  keeps?: boolean
  /**
   * Whether the life only inspects its record; false when unsaid. Such a life keeps nothing, enables no new
   * extension and asks no model, and the ears that do work, the files, the commands and time, are silent under
   * their names, so it runs no command and touches no file.
   */
  inspecting?: boolean
  /**
   * Whether the life enables at its tip the extensions that the configs turn on; true when unsaid. A life runs what
   * its record enables either way.
   */
  extensions?: boolean
  /**
   * The config directory of the user, which the configs and the official extensions read; the one of this process
   * when unsaid.
   */
  config?: string
  /**
   * The actor a prompt goes to when it names none, as the catalog names a model, and an effort after a slash, at its
   * level as [`world::Model::at`] moves it; the first model of the roster when unsaid.
   */
  actor?: string
  /**
   * The models the provider offers beside the model of the actor, as the catalog names them. When it is unsaid, the
   * model of the actor stands alone, or the first model the catalog offers when the actor is unsaid too; a roster
   * that names none, with no actor, offers the operator alone.
   */
  roster?: Array<string>
  /** The claude command line to run, in place of the one that `FURB_CLAUDE_BIN` names or this machine holds. */
  claude?: string
  /** How many seconds a turn of the claude command line may go with no progress. */
  stall?: number
  /** The directory of the images that a turn names. */
  images?: string
  /** A function of the host that answers each request in place of the models. */
  answer?: (request: { actor: string; chain: string; messages: unknown[]; settings: Record<string, unknown> }, write: (delta: { text?: string; thinking?: string }) => void) => Promise<unknown>
  /** A function of the host that is told what a model writes, as it writes it. */
  stream?: (rung: string, chain: string, text: string, thinking: string) => void
}

/** OPERATOR is the name of the operator in the roster and as an actor. */
export declare const OPERATOR: string

/** What an act came to, and whether it is done: nothing while it lives. */
export interface Outcome {
  done: boolean
  value: unknown
}

/** ROOT is the name of the root, which every life opens first under that one name, and on which boot stands the life. */
export declare const ROOT: string

/** Every shape the operator answers, by its name. */
export declare function shapes(): Array<string>

/** The POSIX shell that runs a command of this machine, which a host runs its own commands in too. */
export declare function shell(): string

/** The ear of the skills extension, which finds skills in the folders of a chain and in the config directory. */
export declare function skills(config: string): NativeEar

/**
 * The record at a path, read under its lease, and the ear of the store, which keeps on it what the journal says to
 * keep.
 */
export declare function store(path: string): [unknown[], NativeEar]

/**
 * The system prompt of every model: the engine minified in layout alone, and nothing else.
 *
 * The build makes it from [`ENGINE`], and stops unless it is the same program.
 */
export declare const SYSTEM: string

/** The ear of time, which reads the clock, draws a chance, and ends a wait. */
export declare function time(): NativeEar

/** TIMEOUT is the timeout, in seconds, of a command that does not say one. */
export declare const TIMEOUT: number

/** WINDOW is the window, in tokens, of a model whose roster entry does not say one. */
export declare const WINDOW: number
