/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A named act. Keep its id for controls, or await the act for its outcome. */
export declare class Act {
  get id(): string
  toString(): string
  toJSON(): string
  then<R = unknown, E = never>(onfulfilled?: ((value: unknown) => R | PromiseLike<R>) | null, onrejected?: ((reason: unknown) => E | PromiseLike<E>) | null): Promise<R | E>
}
export type JsAct = Act

export declare class Life {
  /** Open on JavaScript ears, using the same call and reply protocol as the Python binding. */
  static boot(callback: (request: unknown[]) => unknown, names: string[], record?: unknown[] | null): Life
  get root(): string
  /** What boot raised, and nothing when it raised nothing. After a drift the life goes on, with nothing kept. */
  get raised(): { is: string; args: unknown[] } | null
  get disposed(): boolean
  site(value?: string | undefined | null): string
  /** Call any public engine verb, including verbs used by extensions. */
  call<T = unknown>(name: string, args: unknown[], kwargs: Record<string, unknown>): T
  /** Await one act. JavaScript continues to drive the World while the Promise waits. */
  result<T = unknown>(id: string): Promise<T>
  outcome(id: string): Outcome
  held<T = unknown>(name: string, keys: unknown[], ask: string): T
  made<T = unknown>(id: number, args: unknown[], kwargs: Record<string, unknown>): T
  forget(id: number): void
  prompt<T = unknown>(shape: string, message: string, options?: PromptOptions | undefined | null): Act & PromiseLike<T>
  rung(word: string, options?: RungOptions | undefined | null): Act & PromiseLike<unknown>
  /**
   * Read one name from the chain without calling it, with its Python type and representation. The value crosses
   * as every value of the life does, through the stand-in, so a map that holds the key `is` crosses as its pairs.
   */
  inspect(name: string, chain?: string | undefined | null): Inspection
  chain(label: string, source?: string | null, filter?: unknown, on?: string | null): Act & PromiseLike<never>
  grant(options: GrantOptions): Act & PromiseLike<null>
  bash(command: string, options?: BashOptions | undefined | null): Act & PromiseLike<ExitValue>
  wait(seconds: number, chain?: string | undefined | null): Act & PromiseLike<null>
  read<T = TextValue>(path: string, show?: unknown, chain?: string | null): T
  write<T = TextValue>(text: TextValue, chain?: string | undefined | null): T
  peek<T = unknown>(id: string, chain?: string | undefined | null): T | null
  get(id: string): [string, string, string, string, ...unknown[]]
  /** The turns of a chain, each the python a model reads, which the engine wrote. */
  turns(chain?: string | undefined | null): Array<['user' | 'assistant', string, [number, number, number, number, number] | null, unknown]>
  scope(id: string): string
  cwd(chain?: string | undefined | null): string
  cd(path: string, chain?: string | undefined | null): string
  clock(chain?: string | undefined | null): number
  chance(chain?: string | undefined | null): number
  gate(word: string, chain?: string | undefined | null): Array<string>
  pause(id: string): void
  wake(id: string): void
  cancel(id: string): void
  close(value: unknown, id: string): void
  send(kind: string, about: string, words: Array<any>, by?: string | undefined | null): [string, string, string, ...unknown[]]
  span(lo: number, hi: number): { is: 'made'; id: number }
  grep(pattern: string): { is: 'made'; id: number }
  differs(lines: Array<string>): { is: 'made'; id: number }
  take(ids: Array<string>, inside?: boolean | undefined | null): { is: 'made'; id: number }
  /** Drop this sandbox and reject pending waits. The World must stop its own processes and timers. */
  dispose(): void
}
export type JsLife = Life

/**
 * The lease of one record: a lock on the file beside the record, `<record>.lock`, which the process holds until
 * it disposes the lease or ends. The kernel ends the lease of a process that ends, whatever the process number
 * says after it. The holder may move or remove the file, as a delete of the record does.
 */
export declare class RecordLock {
  /** The lease of the record at this path, or the refusal when another holds it. */
  constructor(path: string)
  /** The record the lease is of. */
  get path(): string
  /** The lease ended: the lock is released, and another process may take it. */
  dispose(): void
}

export interface BashOptions {
  fed?: boolean
  timeout?: number
  show?: any
  showErr?: any
  on?: string
}

export declare function decodeRecord(line: string): unknown

export declare function engineSource(): string

export interface ExitValue {
  code?: number
  stdout: TextValue
  stderr: TextValue
}

export interface GrantOptions {
  usd?: number
  share?: number
  on?: string
}

export interface Inspection {
  name: string
  kind: string
  representation: string
  value?: unknown
}

/**
 * Call back when the console of Windows ends this process: at Ctrl+Break, at the close of the console, at a logoff
 * and at a shutdown, with the name of the event: `break`, `close`, `logoff` or `shutdown`. The system holds the
 * process until the callback ends it, or, at a close, a logoff or a shutdown, until the system's own limit. A later
 * callback replaces an earlier one. Ctrl+C stays SIGINT, which the host hears as a signal. A system that is not
 * Windows has no such console, and gives this callback no event.
 */
export declare function onConsoleEnd(callback: (event: "break" | "close" | "logoff" | "shutdown") => void): void

export interface Outcome {
  done: boolean
  value: unknown
}

export interface PromptOptions {
  to?: string
  on?: string
}

export interface RungOptions {
  retells?: string
  actor?: string
  on?: string
}

export interface TextValue {
  path: string
  content: string
}
