/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A named act. Keep its id for controls, or await the act for its outcome. */
export declare class Act {
  get id(): string
  toString(): string
  toJSON(): string
  then<R = unknown, E = never>(onfulfilled?: ((value: unknown) => R | PromiseLike<R>) | null, onrejected?: ((reason: unknown) => E | PromiseLike<E>) | null): Promise<R | E>
}
export type JsAct = Act

export declare class Life {
  /** Open on JavaScript ears, using the same call and reply protocol as the Python binding. */
  static boot(callback: (request: unknown[]) => unknown, names: string[], record?: unknown[] | null): Life
  get root(): string
  get disposed(): boolean
  site(value?: string | undefined | null): string
  /** Call any public engine verb, including verbs used by extensions. */
  call<T = unknown>(name: string, args: unknown[], kwargs: Record<string, unknown>): T
  /** Await one act. JavaScript continues to drive the World while the Promise waits. */
  result<T = unknown>(id: string): Promise<T>
  outcome(id: string): Outcome
  held<T = unknown>(name: string, keys: unknown[], ask: string): T
  made<T = unknown>(id: number, args: unknown[], kwargs: Record<string, unknown>): T
  forget(id: number): void
  prompt<T = unknown>(shape: string, message: string, options?: PromptOptions | undefined | null): Act & PromiseLike<T>
  rung(word: string, options?: RungOptions | undefined | null): Act & PromiseLike<unknown>
  /** Read one name from the chain without calling it. Unrepresentable values still expose their Python repr. */
  inspect(name: string, chain?: string | undefined | null): Inspection
  chain(label: string, source?: string | null, filter?: unknown, on?: string | null): Act & PromiseLike<never>
  grant(options: GrantOptions): Act & PromiseLike<null>
  bash(command: string, options?: BashOptions | undefined | null): Act & PromiseLike<ExitValue>
  wait(seconds: number, chain?: string | undefined | null): Act & PromiseLike<null>
  read<T = TextValue>(path: string, show?: unknown, chain?: string | null): T
  write<T = TextValue>(text: TextValue, chain?: string | undefined | null): T
  peek<T = unknown>(id: string, chain?: string | undefined | null): T | null
  get(id: string): [string, string, string, string, ...unknown[]]
  turns(chain?: string | undefined | null): Array<['user' | 'assistant', Array<string | [string, Array<[string, unknown]>, unknown]>, [number, number, number, number, number] | null, unknown]>
  /** Exact model text, rendered before Python values cross to JavaScript. */
  rendered(chain?: string | undefined | null): Array<string>
  scope(id: string): string
  cwd(chain?: string | undefined | null): string
  cd(path: string, chain?: string | undefined | null): string
  clock(chain?: string | undefined | null): number
  chance(chain?: string | undefined | null): number
  gate(word: string, chain?: string | undefined | null): Array<string>
  pause(id: string): void
  wake(id: string): void
  cancel(id: string): void
  close(value: unknown, id: string): void
  send(kind: string, about: string, words: Array<any>, by?: string | undefined | null): [string, string, string, ...unknown[]]
  span(lo: number, hi: number): { is: 'made'; id: number }
  grep(pattern: string): { is: 'made'; id: number }
  differs(lines: Array<string>): { is: 'made'; id: number }
  take(ids: Array<string>, inside?: boolean | undefined | null): { is: 'made'; id: number }
  /** Drop this sandbox and reject pending waits. The World must stop its own processes and timers. */
  dispose(): void
}
export type JsLife = Life

export interface BashOptions {
  fed?: boolean
  timeout?: number
  show?: any
  showErr?: any
  on?: string
}

export declare function decodeRecord(line: string): unknown

export declare function engineSource(): string

export interface ExitValue {
  code?: number
  stdout: TextValue
  stderr: TextValue
}

export interface GrantOptions {
  usd?: number
  share?: number
  on?: string
}

export interface Inspection {
  name: string
  kind: string
  representation: string
  value?: unknown
}

export interface Outcome {
  done: boolean
  value: unknown
}

export interface PromptOptions {
  to?: string
  on?: string
}

export interface RungOptions {
  retells?: string
  actor?: string
  returns?: string
  on?: string
}

export interface TextValue {
  path: string
  content: string
}
