/** Names, labels, arguments, and help for every slash command. An argument in angle brackets is needed, and one in
 * square brackets may be left out. */
export const commands = {
  new: ["New session", "", "Start a fresh life"],
  model: ["Choose model", "[model]", "Choose the model that answers on this chain"],
  effort: ["Choose effort", "[level]", "Set the reasoning effort of the selected model"],
  shape: ["Response shape", "[type]", "Choose the result type of the next prompt"],
  theme: ["Color theme", "[name]", "Change the palette of every surface"],
  chain: ["New chain", "<label>", "A conversation with its own state"],
  fork: ["Fork chain", "<label>", "Copy this chain's current transcript and program"],
  tree: ["Session tree", "", "Browse the chains and their turns, and open or branch from one"],
  rewind: ["Rewind", "", "Branch from an earlier message or act of this chain"],
  undo: ["Undo message", "", "Remove the last user message from a new transcript branch"],
  redo: ["Redo message", "", "Return to the branch before undo"],
  queue: ["Queue follow-up", "[text]", "Send after current work, or manage queued messages"],
  files: ["Attach file", "", "Search project files for an @ reference"],
  image: ["Attach image", "[path]", "Attach an image file, or paste one from the clipboard"],
  editor: ["External editor", "", "Edit this draft with VISUAL or EDITOR"],
  run: ["Run Python", "<python>", "Write a rung through the gate"],
  bash: ["Run command", "<command>", "Stream a shell command"],
  read: ["Read file", "<path>", "Show a file to this chain"],
  cd: ["Change directory", "<path>", "Change this chain's working directory"],
  edit: ["Edit program", "[prompt id]", "Change a prompt's program and replay it"],
  inspect: ["Inspect a name", "<name>", "Read a value from this chain's module"],
  details: ["Details", "", "Expand or collapse an act in the current view"],
  grant: ["Set budget", "<dollars>", "Pause at a dollar ceiling"],
  context: ["Set context ceiling", "<fraction>", "Pause at a share of the model window"],
  pause: ["Pause chain", "[id]", "Hold delivery while work completes"],
  wake: ["Resume chain", "[id]", "Deliver pending work"],
  cancel: ["Cancel work", "[id]", "End an act or the selected chain's work"],
  feed: ["Feed command", "<id> [text]", "Send a line of input to a command; no text closes its input"],
  close: ["Answer an act", "<id> <json>", "Close an act with a JSON value"],
  name: ["Name this session", "<name>", "Set a name in the session picker"],
  share: ["Share conversation", "[path]", "Export a standalone HTML conversation"],
  export: ["Export transcript", "<path>", "Write the transcript and program to a new JSON file"],
  workspace: ["Open workspace", "[path]", "Choose a workspace or add a project folder"],
  sidebar: ["Toggle sidebar", "", "Show or hide the chains, the usage, and the workspaces"],
  delete: ["Delete session", "", "Move a session and its files to the workspace trash"],
  autocollapse: ["Automatic rung collapse", "", "Toggle collapse of completed rungs"],
  extension: ["Load extension", "<path>", "Load commands from a TypeScript or JavaScript extension"],
  exit: ["Exit", "", "Save every session and quit"],
} as const;
