/** Names, labels, arguments, and help for every slash command. */
export const commands = {
  new: ["New session", "", "Start a fresh life"],
  exit: ["Exit", "", "Save every session and quit"],
  workspace: ["Open workspace", "[path]", "Choose a workspace or add a project folder"],
  sidebar: ["Toggle left sidebar", "", "Show or hide the workspace and session tree"],
  delete: ["Delete session", "", "Move a session and its files to the workspace trash"],
  tree: ["Session tree", "", "Browse this session's chains by their parent source"],
  undo: ["Undo message", "", "Remove the last user message from a new transcript branch"],
  redo: ["Redo message", "", "Return to the branch before undo"],
  editor: ["External editor", "", "Edit this draft with VISUAL or EDITOR"],
  files: ["Attach file", "", "Search project files for an @ reference"],
  queue: ["Queue follow-up", "[text]", "Send after current work, or manage queued messages"],
  share: ["Share conversation", "[path]", "Export a standalone HTML conversation"],
  image: ["Attach image", "[path]", "Attach an image file, or paste one from the clipboard"],
  autocollapse: ["Automatic rung collapse", "", "Toggle collapse of completed rungs"],
  extension: ["Load extension", "path", "Load commands from a TypeScript or JavaScript extension"],
  name: ["Name this session", "name", "Set a name in the session picker"],
  chain: ["New chain", "label", "A conversation with its own state"],
  fork: ["Fork chain", "label", "Copy this chain's current transcript and program"],
  details: ["Details", "", "Expand or collapse an act in the current view"],
  rewind: ["Rewind transcript", "", "Choose the last act the new chain should read"],
  pause: ["Pause chain", "[id]", "Hold delivery while work completes"],
  wake: ["Resume chain", "[id]", "Deliver pending work"],
  cancel: ["Cancel work", "[id]", "End an act or the selected chain's work"],
  grant: ["Set budget", "dollars", "Pause at a dollar ceiling"],
  context: ["Set context ceiling", "fraction", "Pause at a share of the model window"],
  run: ["Run Python", "python", "Write a rung through the gate"],
  bash: ["Run command", "command", "Stream a shell command"],
  read: ["Read file", "path", "Show a file to this chain"],
  cd: ["Change directory", "path", "Change this chain's working directory"],
  edit: ["Edit program", "[prompt id]", "Change a prompt's program and replay it"],
  feed: ["Feed command", "id text", "Send input to a command; empty text closes input"],
  close: ["Answer an act", "id JSON", "Close an act with a JSON value"],
  export: ["Export transcript", "path", "Write the transcript and program to a new JSON file"],
  model: ["Choose model", "[model]", "Use a model from this chain's roster"],
  effort: ["Choose effort", "[level]", "Set the reasoning effort of the selected model"],
  shape: ["Response shape", "type", "Choose the result type of the next prompt"],
  inspect: ["Inspect a name", "name", "Read a value from this chain's module"],
  theme: ["Color theme", "name", "Change the palette of every surface"],
} as const;
